export const CHATGPT_DOMAIN_URL = "https://chat.openai.com";

export const styles = {
  P_PAGE: "12px",
  COLOR_DARK_1: "rgb(52, 53, 65)",
  COLOR_DARK_2: "rgb(32, 33, 35)",
  COLOR_WHITE_1: "rgb(217, 217, 227)",
  COLOR_CARD_BORDER: "rgba(255,255,255,0.2)",
  BG_CARD_HOVER: "rgba(115,115,115,0.1)",
};

export const MESSAGE_ACTIONS = {
  START_FETCHING_CONVERSATIONS: "START_FETCHING_CONVERSATIONS",
  UPDATE_FETCHING_CONVERSATIONS: "UPDATE_FETCHING_CONVERSATIONS",
  FINISH_FETCHING_CONVERSATIONS: "FINISH_FETCHING_CONVERSATIONS",
  START_FETCHING_CONVERSATION_DETAIL: "START_FETCHING_CONVERSATION_DETAIL",
  UPDATE_FETCHING_CONVERSATION_DETAIL: "UPDATE_FETCHING_CONVERSATION_DETAIL",
  FINISH_FETCHING_CONVERSATION_DETAIL: "FINISH_FETCHING_CONVERSATION_DETAIL",
};
