export const CHATGPT_DOMAIN_URL = "https://chat.openai.com";
export const FEEDBACK_URL =
  "https://docs.google.com/forms/d/e/1FAIpQLSdFSu2NKqraFu0mjyfxaZ8QL6BB275iJhRdUjupug0QfRh1_Q/viewform?usp=sf_link";

export const ACCESS_TOKEN_KEY = "accessToken";

export const styles = {
  P_PAGE: "12px",
  COLOR_DARK_1: "rgb(52, 53, 65)",
  COLOR_DARK_2: "rgb(32, 33, 35)",
  COLOR_WHITE_1: "rgb(217, 217, 227)",
  COLOR_CARD_BORDER: "rgba(255,255,255,0.2)",
  BG_CARD_HOVER: "rgba(115,115,115,0.1)",
  PANEL_LINE_HEIGHT: "44px",
};

export const MESSAGE_ACTIONS = {
  INIT: "INIT",
  REFRESH: "REFRESH",

  FETCH_CONVERSATIONS: "FETCH_CONVERSATIONS",
  FETCH_FOLDERS: "FETCH_FOLDERS",

  // conversation actions
  RENAME_CONVERSATION: "RENAME_CONVERSATION",

  // bg to content
  APPEND_CONVERSATIONS: "APPEND_CONVERSATIONS",
  APPEND_FOLDERS: "APPEND_FOLDERS",

  // folders creation
  CREATE_NEW_FOLDER: "CREATE_NEW_FOLDER", // content to bg
  ADD_CONVERSATIONS_TO_FOLDER: "ADD_CONVERSATIONS_TO_FOLDER",
  RENAME_FOLDER: "RENAME_FOLDER",
  DELETE_FOLDER: "DELETE_FOLDER",

  // folder & conversation actions
  DELETE_CONVERSATIONS_FROM_FOLDER: "DELETE_CONVERSATIONS_FROM_FOLDER",

  RESPONSE_STATUS: "RESPONSE_STATUS",
  STATUS_SUCCESS: "STATUS_SUCCESS",

  SEARCH: "SEARCH",

  // conversation detail update progress
  PROGRESS: "PROGRESS",

  // =============== Pinned Conversations ================

  // content to bg: toggle pin conversation
  // bg to content: update pinned conversations
  PIN_CONVERSATION: "PIN_CONVERSATION",

  FETCHING_APP_STATE: "FETCHING_APP_STATE",
  SAVE_APP_STATE: "SAVE_APP_STATE",

  // =============== URL Changes ================
  CURRENT_CONVERSATION_CHANGE: "CURRENT_CONVERSATION_URL_CHANGE",

  UPDATE_FETCHING_CONVERSATIONS: "UPDATE_FETCHING_CONVERSATIONS",
  FINISH_FETCHING_CONVERSATIONS: "FINISH_FETCHING_CONVERSATIONS",
  START_FETCHING_CONVERSATION_DETAIL: "START_FETCHING_CONVERSATION_DETAIL",
  UPDATE_FETCHING_CONVERSATION_DETAIL: "UPDATE_FETCHING_CONVERSATION_DETAIL",
  FINISH_FETCHING_CONVERSATION_DETAIL: "FINISH_FETCHING_CONVERSATION_DETAIL",

  FETCH_FILTERED_CONVERSATIONS: "FETCH_FILTERED_CONVERSATIONS",
  FINISH_SEARCHING_CONVERSATIONS: "FINISH_SEARCHING_CONVERSATIONS",

  TOGGLE_PANEL: "TOGGLE_PANEL",
};

export const CTRL_KEY = "Control";
export const ALT_KEY = "Alt";

export const CONTENT_VIEW_CONTAINER_ID =
  "chatgpt-archive-content-view-container";

export const SORT_BY = {
  UPDATE_TIME: "update_time",
  CREATE_TIME: "create_time",
};

export const LOCAL_STORAGE_KEYS = {
  DARK_MODE: "darkModeEnabled",
};

export const DARK_MODE_VALUES = {
  DARK: "true",
  LIGHT: "false",
};
